//
// Created by kigor on 07.08.2023.
//

#ifndef PROJECT_OOP_FINANCEMANAGER_FINANCEMANAGER_H
#define PROJECT_OOP_FINANCEMANAGER_FINANCEMANAGER_H


class FinanceManager {

};


#endif //PROJECT_OOP_FINANCEMANAGER_FINANCEMANAGER_H
